/*
    SuperGAMESDataBase Oracle
*/

CREATE TABLE USERS
(

    Pseudo VARCHAR2(30)
        CONSTRAINT PKusers PRIMARY KEY,

    SurName VARCHAR2(30),

    FirstName VARCHAR2(30),

    Password VARCHAR2(100)

);

CREATE TABLE GAMES
(

    Name VARCHAR2(30)
        CONSTRAINT PKGAMESs PRIMARY KEY,

    Creator VARCHAR2(30)

);

CREATE TABLE RESULTS
(

    IdResult NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT PKresults PRIMARY KEY,

    Points NUMBER(3),

    DateResult TIMESTAMP,

    IdGAMES NUMBER(3)
        CONSTRAINT FKresultsGAMESs REFERENCES GAMES(Name),

    IdUser VARCHAR2(30)
        CONSTRAINT FKresultsUsers REFERENCES USERS(Pseudo)

);

INSERT INTO GAMES (Name, Creator)
VALUES ('BusterGhost', 'Malchair Valentin');

INSERT INTO GAMES (Name, Creator)
VALUES ('FroggyJump', 'Lecock Simon');

INSERT INTO GAMES (Name, Creator)
VALUES ('AimTrainer', 'Discart Gauthier');

INSERT INTO GAMES (Name, Creator)
VALUES ('2048', 'Richard Lukas');

INSERT INTO GAMES (Name, Creator)
VALUES ('???', 'Verstringe Ethan');

/*
    SuperGAMESDataBase MySql
*/
DROP TABLE USERS;
DROP TABLE GAMES;
DROP TABLE RESULTS;

CREATE TABLE USERS (
    Pseudo VARCHAR(30) PRIMARY KEY,
    SurName VARCHAR(30),
    FirstName VARCHAR(30),
    Password VARCHAR(100)
);

CREATE TABLE GAMES (
    Name VARCHAR(30) PRIMARY KEY,
    Creator VARCHAR(30)
);

CREATE TABLE RESULTS (
     IdResult INT AUTO_INCREMENT PRIMARY KEY,
     Points INT(3),
     DateResult TIMESTAMP,
     IdGAMES VARCHAR(30),
     IdUser VARCHAR(30),
     FOREIGN KEY (IdGAMES) REFERENCES GAMES(Name),
     FOREIGN KEY (IdUser) REFERENCES USERS(Pseudo)
);

INSERT INTO GAMES (Name, Creator)
VALUES ('BusterGhost', 'Malchair Valentin'),
('FroggyJump', 'Lecock Simon'),
('AimTrainer', 'Discart Gauthier'),
('2048', 'Richard Lukas'),
('IndiannaDungeon', 'Verstringe Ethan');
