CREATE TABLE USER
(

    IdUser NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT PKuser PRIMARY KEY,
        
    SurName VARCHAR2(30),
    
    FirstName VARCHAR2(30),
    
    Pseudo VARCHAR2(30),
    
    Password VARCHAR2(30)
    
);

CREATE TABLE GAME
(

    IdGame NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT PKgame PRIMARY KEY,
    
    Name VARCHAR2(30),
    
    Creator VARCHAR2(30)
        
);

CREATE TABLE RESULT
(

    IdResult NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT PKresult PRIMARY KEY,

    Points NUMBER(3),
    
    Date TIMESTAMP,
    
    IdGame NUMBER(3)
        CONSTRAINT FKresultGame REFERENCES GAME(IdGame),
        
    IdUser NUMBER(3)
        CONSTRAINT FKresultUser REFERENCES USER(IdUser)

);

INSERT INTO GAME (IdGame, Name, Creator)
VALUES (NULL, 'BusterGhost', 'Malchair Valentin');

INSERT INTO GAME (IdGame, Name, Creator)
VALUES (NULL, 'FroggyJump', 'Lecock Simon');

INSERT INTO GAME (IdGame, Name, Creator)
VALUES (NULL, 'AimTrainer', 'Discart Gauthier');

INSERT INTO GAME (IdGame, Name, Creator)
VALUES (NULL, '???', 'Richard Lukas');

INSERT INTO GAME (IdGame, Name, Creator)
VALUES (NULL, '???', 'Verstringe Ethan');
