/*
    SuperGAMESDataBase
*/

CREATE TABLE USERS
(

    Pseudo VARCHAR2(30)
        CONSTRAINT PKusers PRIMARY KEY,
        
    SurName VARCHAR2(30),
    
    FirstName VARCHAR2(30),
    
    Password VARCHAR2(30)
    
);

CREATE TABLE GAMES
(

    Name VARCHAR2(30)
        CONSTRAINT PKGAMESs PRIMARY KEY,
    
    Creator VARCHAR2(30)
        
);

CREATE TABLE RESULTS
(

    IdResult NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT PKresults PRIMARY KEY,

    Points NUMBER(3),
    
    DateResult TIMESTAMP,
    
    IdGAMES NUMBER(3)
        CONSTRAINT FKresultsGAMESs REFERENCES GAMES(Name),

    IdUser VARCHAR2(30)
        CONSTRAINT FKresultsUsers REFERENCES USERS(Pseudo)

);

INSERT INTO GAMES (Name, Creator)
VALUES ('BusterGhost', 'Malchair Valentin');

INSERT INTO GAMES (Name, Creator)
VALUES ('FroggyJump', 'Lecock Simon');

INSERT INTO GAMES (Name, Creator)
VALUES ('AimTrainer', 'Discart Gauthier');

INSERT INTO GAMES (Name, Creator)
VALUES ('2048', 'Richard Lukas');

INSERT INTO GAMES (Name, Creator)
VALUES ('???', 'Verstringe Ethan');
